#!/usr/bin/env python3
"""
Identify groups of images that were bracketed.

Note that this process necessarily ignores incomplete sequences (the button was 
not held down long-enough to capture images for the full sequence of exposures).
"""

import argparse
import os

import bif.bracketed

def _get_args():
	parser = \
		argparse.ArgumentParser(description='Process some integers.')
	
	parser.add_argument(
		'path',
		help='Path to scan')

	args = parser.parse_args()
	return args

def _main():
	args = _get_args()
	ba = bif.find_bracketed.BracketedAnalysis()
	for exposure_delta, entries in ba.find_bracketed_images(args.path):
		filenames = [os.path.basename(hi.filepath) for hi in entries]
		print("{} {}".format(exposure_delta, filenames))

if __name__ == '__main__':
	_main()


# TODO(dustin): !! Configure logging.
